app/Http/routes.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/', function () {
        return view('layouts/app_front');
    });
});



Route::group(['middleware' => ['web']], function () {

    Route::auth();

});



Route::group([
    'version'   => 'v1',
    'prefix' => 'front',
    'namespace' => config('generator.namespace_front_controller'),
    'middleware' => ['web','auth']
], function ($front)
{
    include_once __DIR__ . '/front_routes.php';
});


Route::group(['middleware' => ['web','auth']], function () {

    Route::resource('reaUsers', 'ReaUserController');

    Route::get('reaUsers/{id}/delete', [
        'as' => 'reaUsers.delete',
        'uses' => 'ReaUserController@destroy',
    ]);

    //Route::resource('schools', 'SchoolController');
    Route::get('schools/generator', [
        'as' => 'schools.generator',
        'uses' => 'SchoolController@getSearchGenerator',
    ]);
    /*Route::post('schools/generator', [
        'as' => 'schools.generator',
        'uses' => 'SchoolController@postSearchGenerator',
    ]);*/
    Route::get('schools/{id}/delete', [
        'as' => 'schools.delete',
        'uses' => 'SchoolController@destroy',
    ]);

    Route::resource('schoolLevels', 'SchoolLevelController');

    Route::get('schoolLevels/{id}/delete', [
        'as' => 'schoolLevels.delete',
        'uses' => 'SchoolLevelController@destroy',
    ]);

});


/*
|--------------------------------------------------------------------------
| dingo/api and mitulgolakiya/laravel-api-generator api routes
|--------------------------------------------------------------------------
*/

$api = app('api.router');

$api->group([
	'version'   => 'v1',
    'prefix' => 'api',
	'namespace' => config('generator.namespace_api_controller'),
	'middleware' => ['cors']
], function ($api)
{

	include_once __DIR__ . '/api_routes.php';

	$api->get('errors/{id}', function ($id)
	{
		return \Mitul\Generator\Errors::getErrors([$id]);
	});

	$api->get('errors', function ()
	{
		return \Mitul\Generator\Errors::getErrors([], [], true);
	});

	$api->get('/', function ()
	{
		$links = [];

		return ['links' => $links];
	});

});





Route::resource('cities', 'CityController');

Route::get('cities/{id}/delete', [
    'as' => 'cities.delete',
    'uses' => 'CityController@destroy',
]);


Route::resource('classCourses', 'ClassCourseController');

Route::get('classCourses/{id}/delete', [
    'as' => 'classCourses.delete',
    'uses' => 'ClassCourseController@destroy',
]);


Route::resource('countries', 'CountryController');

Route::get('countries/{id}/delete', [
    'as' => 'countries.delete',
    'uses' => 'CountryController@destroy',
]);


Route::resource('courses', 'CourseController');

Route::get('courses/{id}/delete', [
    'as' => 'courses.delete',
    'uses' => 'CourseController@destroy',
]);


Route::resource('dateSystems', 'DateSystemController');

Route::get('dateSystems/{id}/delete', [
    'as' => 'dateSystems.delete',
    'uses' => 'DateSystemController@destroy',
]);


Route::resource('genres', 'GenreController');

Route::get('genres/{id}/delete', [
    'as' => 'genres.delete',
    'uses' => 'GenreController@destroy',
]);


Route::resource('genres', 'GenreController');

Route::get('genres/{id}/delete', [
    'as' => 'genres.delete',
    'uses' => 'GenreController@destroy',
]);


Route::resource('levelClasses', 'LevelClassController');

Route::get('levelClasses/{id}/delete', [
    'as' => 'levelClasses.delete',
    'uses' => 'LevelClassController@destroy',
]);


Route::resource('periods', 'PeriodController');

Route::get('periods/{id}/delete', [
    'as' => 'periods.delete',
    'uses' => 'PeriodController@destroy',
]);


Route::resource('schoolTypes', 'SchoolTypeController');

Route::get('schoolTypes/{id}/delete', [
    'as' => 'schoolTypes.delete',
    'uses' => 'SchoolTypeController@destroy',
]);


Route::resource('schoolYears', 'SchoolYearController');

Route::get('schoolYears/{id}/delete', [
    'as' => 'schoolYears.delete',
    'uses' => 'SchoolYearController@destroy',
]);


Route::resource('tServices', 'TServiceController');

Route::get('tServices/{id}/delete', [
    'as' => 'tServices.delete',
    'uses' => 'TServiceController@destroy',
]);


Route::resource('alerts', 'AlertController');

Route::get('alerts/{id}/delete', [
    'as' => 'alerts.delete',
    'uses' => 'AlertController@destroy',
]);


Route::resource('attendances', 'AttendanceController');

Route::get('attendances/{id}/delete', [
    'as' => 'attendances.delete',
    'uses' => 'AttendanceController@destroy',
]);


Route::resource('attendanceStatuses', 'AttendanceStatusController');

Route::get('attendanceStatuses/{id}/delete', [
    'as' => 'attendanceStatuses.delete',
    'uses' => 'AttendanceStatusController@destroy',
]);


Route::resource('attendanceTypes', 'AttendanceTypeController');

Route::get('attendanceTypes/{id}/delete', [
    'as' => 'attendanceTypes.delete',
    'uses' => 'AttendanceTypeController@destroy',
]);


Route::resource('classCourseExams', 'ClassCourseExamController');

Route::get('classCourseExams/{id}/delete', [
    'as' => 'classCourseExams.delete',
    'uses' => 'ClassCourseExamController@destroy',
]);


Route::resource('courseSessions', 'CourseSessionController');

Route::get('courseSessions/{id}/delete', [
    'as' => 'courseSessions.delete',
    'uses' => 'CourseSessionController@destroy',
]);


Route::resource('eFiles', 'EFileController');

Route::get('eFiles/{id}/delete', [
    'as' => 'eFiles.delete',
    'uses' => 'EFileController@destroy',
]);


Route::resource('examSessions', 'ExamSessionController');

Route::get('examSessions/{id}/delete', [
    'as' => 'examSessions.delete',
    'uses' => 'ExamSessionController@destroy',
]);


Route::resource('idnTypes', 'IdnTypeController');

Route::get('idnTypes/{id}/delete', [
    'as' => 'idnTypes.delete',
    'uses' => 'IdnTypeController@destroy',
]);


Route::resource('modelTerms', 'ModelTermController');

Route::get('modelTerms/{id}/delete', [
    'as' => 'modelTerms.delete',
    'uses' => 'ModelTermController@destroy',
]);


Route::resource('ratings', 'RatingController');

Route::get('ratings/{id}/delete', [
    'as' => 'ratings.delete',
    'uses' => 'RatingController@destroy',
]);


Route::resource('schoolClasses', 'SchoolClassController');

Route::get('schoolClasses/{id}/delete', [
    'as' => 'schoolClasses.delete',
    'uses' => 'SchoolClassController@destroy',
]);


Route::resource('schoolEmployees', 'SchoolEmployeeController');

Route::get('schoolEmployees/{id}/delete', [
    'as' => 'schoolEmployees.delete',
    'uses' => 'SchoolEmployeeController@destroy',
]);


Route::resource('schoolLevels', 'SchoolLevelController');

Route::get('schoolLevels/{id}/delete', [
    'as' => 'schoolLevels.delete',
    'uses' => 'SchoolLevelController@destroy',
]);


Route::resource('schoolMemberDays', 'SchoolMemberDayController');

Route::get('schoolMemberDays/{id}/delete', [
    'as' => 'schoolMemberDays.delete',
    'uses' => 'SchoolMemberDayController@destroy',
]);


Route::resource('schoolPeriods', 'SchoolPeriodController');

Route::get('schoolPeriods/{id}/delete', [
    'as' => 'schoolPeriods.delete',
    'uses' => 'SchoolPeriodController@destroy',
]);


Route::resource('schoolTerms', 'SchoolTermController');

Route::get('schoolTerms/{id}/delete', [
    'as' => 'schoolTerms.delete',
    'uses' => 'SchoolTermController@destroy',
]);


Route::resource('sessionStatuses', 'SessionStatusController');

Route::get('sessionStatuses/{id}/delete', [
    'as' => 'sessionStatuses.delete',
    'uses' => 'SessionStatusController@destroy',
]);


Route::resource('langs', 'LanguageController');

Route::get('langs/{id}/delete', [
    'as' => 'langs.delete',
    'uses' => 'LanguageController@destroy',
]);



Route::resource('ratings', 'RatingController');

Route::get('ratings/{id}/delete', [
    'as' => 'ratings.delete',
    'uses' => 'RatingController@destroy',
]);


Route::resource('hijraDateBases', 'HijraDateBaseController');

Route::get('hijraDateBases/{id}/delete', [
    'as' => 'hijraDateBases.delete',
    'uses' => 'HijraDateBaseController@destroy',
]);


Route::resource('courseSchedItems', 'CourseSchedItemController');

Route::get('courseSchedItems/{id}/delete', [
    'as' => 'courseSchedItems.delete',
    'uses' => 'CourseSchedItemController@destroy',
]);

app/Models/CourseSession.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model as Model;

class CourseSession extends Model
{
    
	public $table = "course_session";
    

	public $fillable = [
	    "session_hdate",
		"session_end_time",
		"session_start_time",
		"course_id",
		"level_class_id",
		"prof_id",
		"school_id",
		"session_status_id",
		"session_status_comment",
		"symbol",
		"year"
	];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        "id" => "integer",
		"created_by" => "integer",
		"updated_by" => "integer",
		"validated_by" => "integer",
		"active" => "string",
		"version" => "integer",
		"update_groups_mfk" => "string",
		"delete_groups_mfk" => "string",
		"display_groups_mfk" => "string",
		"sci_id" => "integer",
		"session_hdate" => "string",
		"session_end_time" => "string",
		"session_start_time" => "string",
		"course_id" => "integer",
		"level_class_id" => "integer",
		"prof_id" => "integer",
		"school_id" => "integer",
		"session_status_id" => "integer",
		"session_status_comment" => "string",
		"symbol" => "string",
		"year" => "string"
    ];

	public static $rules = [
	    
	];

	/**
	 * Display a listing of the CourseSession of one day.
	 * POST|HEAD /courseSessions/isExist
	 *
	 * @return Response
	 */
	public static function isExist(array $course_session)
	{
		extract($course_session);
		$nb = CourseSession::where('group_num','=',$group_num)
			->where('school_id','=',$school_id)
			->where('year','=',$year)
			->where('hmonth','=',$hmonth)
			->where('hday_num','=',$hday_num)
			->where('level_class_id','=',$level_class_id)
			->where('symbol','=',$symbol)
			->where('session_order','=',$session_order)
			->get()->count();

		if($nb > 0)
			return true;
		else
			return false;
	}

	public static function checkStatusCourseSession($status_id, array $course_session)
	{
		extract($course_session);
		$course_session = CourseSession::where('prof_id', $prof_id)
										->where('session_status_id',$status_id)
										->where('group_num','=',$group_num)
										->where('school_id','=',$school_id)
										->where('year','=',$year)
										->where('hmonth','=',$hmonth)
										->where('hday_num','=',$hday_num)
										->where('level_class_id','=',$level_class_id)
										->where('symbol','=',$symbol)
										->first();
		return $course_session;
	}


	public static function checkIfIsOwnerAnTeacher(array $course_session)
	{
		extract($course_session);
		$result = CourseSession::join('school_employee','school_employee.rea_user_id','=','course_session.prof_id')
								->where('course_session.group_num','=',$group_num)
								->where('course_session.school_id','=',$school_id)
								->where('course_session.year','=',$year)
								->where('course_session.hmonth','=',$hmonth)
								->where('course_session.hday_num','=',$hday_num)
								->where('course_session.level_class_id','=',$level_class_id)
								->where('course_session.symbol','=',$symbol)
								->where('course_session.session_order','=',$session_order)
								->where('course_session.session_status_id', Session_status_Coming_session)
								->where('school_employee.school_job_mfk','like','%,'.School_Job_Teacher.',%')
								->first();
		return $result;
	}

	public static function updateCourseSession(array $course_session,array $attributes)
	{
		extract($course_session);
		$result = CourseSession::where('prof_id', $prof_id)
					->where('session_status_id',$session_status_id)
					->where('group_num','=',$group_num)
					->where('school_id','=',$school_id)
					->where('year','=',$year)
					->where('hmonth','=',$hmonth)
					->where('hday_num','=',$hday_num)
					->where('level_class_id','=',$level_class_id)
					->where('symbol','=',$symbol)
					->where('session_order','=',$session_order)
					->update($attributes);
		return $result;
	}

}

app/Http/Controllers/CourseSessionController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CreateCourseSessionRequest;
use App\Http\Requests\UpdateCourseSessionRequest;
use App\Libraries\Repositories\CourseSessionRepository;
use Flash;
use App\Libraries\Reaaya\mitulgolakiya\src\Mitul\Controller\AppBaseController as AppBaseController;
use Response;

class CourseSessionController extends AppBaseController
{

	/** @var  CourseSessionRepository */
	private $courseSessionRepository;

	function __construct(CourseSessionRepository $courseSessionRepo)
	{
		$this->courseSessionRepository = $courseSessionRepo;
	}



	/**
	 * Created By Achraf: 21/03/2016
	 * Get Angular Template Front for timeline course session
	 * Get
	 *
	 * @return View
	 */
	public function getTimelineFrontTpl()
	{
		return view('front.coursesession.timeline');
	}

}

resources/views/courseSessions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::open(['route' => 'courseSessions.store']) !!}

        @include('courseSessions.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/courseSessions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @include('common.errors')

    {!! Form::model($courseSession, ['route' => ['courseSessions.update', $courseSession->id], 'method' => 'patch']) !!}

        @include('courseSessions.fields')

    {!! Form::close() !!}
</div>
@endsection

resources/views/courseSessions/fields.blade.php
<!-- Session Hdate Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('session_hdate', 'Session Hdate:') !!}
	{!! Form::text('session_hdate', null, ['class' => 'form-control']) !!}
</div>

<!-- Session End Time Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('session_end_time', 'Session End Time:') !!}
	{!! Form::text('session_end_time', null, ['class' => 'form-control']) !!}
</div>

<!-- Session Start Time Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('session_start_time', 'Session Start Time:') !!}
	{!! Form::text('session_start_time', null, ['class' => 'form-control']) !!}
</div>

<!-- Course Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('course_id', 'Course Id:') !!}
	{!! Form::number('course_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Level Class Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('level_class_id', 'Level Class Id:') !!}
	{!! Form::number('level_class_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Prof Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('prof_id', 'Prof Id:') !!}
	{!! Form::number('prof_id', null, ['class' => 'form-control']) !!}
</div>

<!-- School Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('school_id', 'School Id:') !!}
	{!! Form::number('school_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Session Status Id Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('session_status_id', 'Session Status Id:') !!}
	{!! Form::number('session_status_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Session Status Comment Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('session_status_comment', 'Session Status Comment:') !!}
	{!! Form::text('session_status_comment', null, ['class' => 'form-control']) !!}
</div>

<!-- Symbol Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('symbol', 'Symbol:') !!}
	{!! Form::text('symbol', null, ['class' => 'form-control']) !!}
</div>

<!-- Year Field -->
<div class="form-group col-sm-6 col-lg-4">
    {!! Form::label('year', 'Year:') !!}
	{!! Form::text('year', null, ['class' => 'form-control']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
</div>

resources/views/courseSessions/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        @include('flash::message')

        <div class="row">
            <h1 class="pull-left">CourseSessions</h1>
            <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('courseSessions.create') !!}">Add New</a>
        </div>

        <div class="row">
            @if($courseSessions->isEmpty())
                <div class="well text-center">No CourseSessions found.</div>
            @else
                @include('courseSessions.table')
            @endif
        </div>

        @include('common.paginate', ['records' => $courseSessions])


    </div>
@endsection

resources/views/courseSessions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	 @include('courseSessions.show_fields')
</div>
@endsection

resources/views/courseSessions/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $courseSession->id !!}</p>
</div>

<!-- Created By Field -->
<div class="form-group">
    {!! Form::label('created_by', 'Created By:') !!}
    <p>{!! $courseSession->created_by !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $courseSession->created_at !!}</p>
</div>

<!-- Updated By Field -->
<div class="form-group">
    {!! Form::label('updated_by', 'Updated By:') !!}
    <p>{!! $courseSession->updated_by !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $courseSession->updated_at !!}</p>
</div>

<!-- Validated By Field -->
<div class="form-group">
    {!! Form::label('validated_by', 'Validated By:') !!}
    <p>{!! $courseSession->validated_by !!}</p>
</div>

<!-- Validated At Field -->
<div class="form-group">
    {!! Form::label('validated_at', 'Validated At:') !!}
    <p>{!! $courseSession->validated_at !!}</p>
</div>

<!-- Active Field -->
<div class="form-group">
    {!! Form::label('active', 'Active:') !!}
    <p>{!! $courseSession->active !!}</p>
</div>

<!-- Version Field -->
<div class="form-group">
    {!! Form::label('version', 'Version:') !!}
    <p>{!! $courseSession->version !!}</p>
</div>

<!-- Update Groups Mfk Field -->
<div class="form-group">
    {!! Form::label('update_groups_mfk', 'Update Groups Mfk:') !!}
    <p>{!! $courseSession->update_groups_mfk !!}</p>
</div>

<!-- Delete Groups Mfk Field -->
<div class="form-group">
    {!! Form::label('delete_groups_mfk', 'Delete Groups Mfk:') !!}
    <p>{!! $courseSession->delete_groups_mfk !!}</p>
</div>

<!-- Display Groups Mfk Field -->
<div class="form-group">
    {!! Form::label('display_groups_mfk', 'Display Groups Mfk:') !!}
    <p>{!! $courseSession->display_groups_mfk !!}</p>
</div>

<!-- Sci Id Field -->
<div class="form-group">
    {!! Form::label('sci_id', 'Sci Id:') !!}
    <p>{!! $courseSession->sci_id !!}</p>
</div>

<!-- Session Hdate Field -->
<div class="form-group">
    {!! Form::label('session_hdate', 'Session Hdate:') !!}
    <p>{!! $courseSession->session_hdate !!}</p>
</div>

<!-- Session End Time Field -->
<div class="form-group">
    {!! Form::label('session_end_time', 'Session End Time:') !!}
    <p>{!! $courseSession->session_end_time !!}</p>
</div>

<!-- Session Start Time Field -->
<div class="form-group">
    {!! Form::label('session_start_time', 'Session Start Time:') !!}
    <p>{!! $courseSession->session_start_time !!}</p>
</div>

<!-- Course Id Field -->
<div class="form-group">
    {!! Form::label('course_id', 'Course Id:') !!}
    <p>{!! $courseSession->course_id !!}</p>
</div>

<!-- Level Class Id Field -->
<div class="form-group">
    {!! Form::label('level_class_id', 'Level Class Id:') !!}
    <p>{!! $courseSession->level_class_id !!}</p>
</div>

<!-- Prof Id Field -->
<div class="form-group">
    {!! Form::label('prof_id', 'Prof Id:') !!}
    <p>{!! $courseSession->prof_id !!}</p>
</div>

<!-- School Id Field -->
<div class="form-group">
    {!! Form::label('school_id', 'School Id:') !!}
    <p>{!! $courseSession->school_id !!}</p>
</div>

<!-- Session Status Id Field -->
<div class="form-group">
    {!! Form::label('session_status_id', 'Session Status Id:') !!}
    <p>{!! $courseSession->session_status_id !!}</p>
</div>

<!-- Session Status Comment Field -->
<div class="form-group">
    {!! Form::label('session_status_comment', 'Session Status Comment:') !!}
    <p>{!! $courseSession->session_status_comment !!}</p>
</div>

<!-- Symbol Field -->
<div class="form-group">
    {!! Form::label('symbol', 'Symbol:') !!}
    <p>{!! $courseSession->symbol !!}</p>
</div>

<!-- Year Field -->
<div class="form-group">
    {!! Form::label('year', 'Year:') !!}
    <p>{!! $courseSession->year !!}</p>
</div>

resources/views/courseSessions/table.blade.php
<table class="table">
    <thead>
    <th>Id</th>
			<th>Created By</th>
			<th>Created At</th>
			<th>Updated By</th>
			<th>Updated At</th>
			<th>Validated By</th>
			<th>Validated At</th>
			<th>Active</th>
			<th>Version</th>
			<th>Update Groups Mfk</th>
			<th>Delete Groups Mfk</th>
			<th>Display Groups Mfk</th>
			<th>Sci Id</th>
			<th>Session Hdate</th>
			<th>Session End Time</th>
			<th>Session Start Time</th>
			<th>Course Id</th>
			<th>Level Class Id</th>
			<th>Prof Id</th>
			<th>School Id</th>
			<th>Session Status Id</th>
			<th>Session Status Comment</th>
			<th>Symbol</th>
			<th>Year</th>
    <th width="50px">Action</th>
    </thead>
    <tbody>
    @foreach($courseSessions as $courseSession)
        <tr>
            <td>{!! $courseSession->id !!}</td>
			<td>{!! $courseSession->created_by !!}</td>
			<td>{!! $courseSession->created_at !!}</td>
			<td>{!! $courseSession->updated_by !!}</td>
			<td>{!! $courseSession->updated_at !!}</td>
			<td>{!! $courseSession->validated_by !!}</td>
			<td>{!! $courseSession->validated_at !!}</td>
			<td>{!! $courseSession->active !!}</td>
			<td>{!! $courseSession->version !!}</td>
			<td>{!! $courseSession->update_groups_mfk !!}</td>
			<td>{!! $courseSession->delete_groups_mfk !!}</td>
			<td>{!! $courseSession->display_groups_mfk !!}</td>
			<td>{!! $courseSession->sci_id !!}</td>
			<td>{!! $courseSession->session_hdate !!}</td>
			<td>{!! $courseSession->session_end_time !!}</td>
			<td>{!! $courseSession->session_start_time !!}</td>
			<td>{!! $courseSession->course_id !!}</td>
			<td>{!! $courseSession->level_class_id !!}</td>
			<td>{!! $courseSession->prof_id !!}</td>
			<td>{!! $courseSession->school_id !!}</td>
			<td>{!! $courseSession->session_status_id !!}</td>
			<td>{!! $courseSession->session_status_comment !!}</td>
			<td>{!! $courseSession->symbol !!}</td>
			<td>{!! $courseSession->year !!}</td>
            <td>
                <a href="{!! route('courseSessions.edit', [$courseSession->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                <a href="{!! route('courseSessions.delete', [$courseSession->id]) !!}" onclick="return confirm('Are you sure wants to delete this CourseSession?')"><i class="glyphicon glyphicon-remove"></i></a>
            </td>
        </tr>
    @endforeach
    </tbody>
</table>